object Versions {
    const val GRADLE_PLUGIN = "7.1.2"
    const val GRADLE_VERSIONS_PLUGIN = "0.42.0"
    const val DETEKT_PLUGIN = "1.20.0"
    const val KOTLIN = "1.6.21"
    const val COMPOSE = "1.2.0-beta02"

    const val APPCOMPAT = "1.4.1"
    const val COMPOSE_ACTIVITY = "1.4.0"
    const val ESPRESSO = "3.4.0"
    const val JUNIT = "4.13.2"
    const val JUNIT_EXT = "1.1.3"
    const val KOIN = "3.2.0"
    const val KOIN_KSP = "1.0.0-beta-2"
    const val KSP = "1.6.21-1.0.5"
    const val KTX_CORE = "1.7.0"
    const val LIFECYCLE = "2.5.0-rc01"
    const val MATERIAL = "1.5.0"
    const val NAVIGATION = "2.4.1"
    const val OKHTTP = "5.0.0-alpha.7"
    const val RETROFIT = "2.9.0"
    const val ROOM = "2.4.2"
    const val SERIALIZATION_CONVERTER = "0.8.0"
    const val SERIALIZATION_JSON = "1.3.3"
    const val TIMBER = "5.0.1"
}
